# Generated by Django 5.2.3 on 2025-06-12 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CVSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('order', models.IntegerField(help_text='Numărul de ordine pentru aranjare', unique=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
